### ISSUE TITLE
Fix `compute_sdss_pca`

### ISSUE THREAD

**Issue by bsipocz** [astroML/astroML#149]
Fix data fetcher in `compute_sdss_pca.py`

These functionalities are not exposed anywhere to the users, there we use the already generated files that is uploaded to `astroML/astroML-data`, but ultimately it would be nice to fix this.

**Comment by bsipocz** [comment]
Almost there:
```
   1 spectra skipped
   4000 spectra processed
saving to spec4000.npz
/Users/bsipocz/munka/devel/astroml/astroML/dimensionality/iterative_pca.py:82: RuntimeWarning: invalid value encountered in true_divide
  X_recons /= np.sqrt(np.sum(X_recons ** 2, 1))[:, None]
 ** On entry to DLASCLS parameter number  4 had an illegal value
 ** On entry to DLASCLS parameter number  4 had an illegal value
Traceback (most recent call last):
  File "examples/datasets/compute_sdss_pca.py", line 139, in <module>
    spec_iterative_pca('spec4000.npz')
  File "examples/datasets/compute_sdss_pca.py", line 122, in spec_iterative_pca
    full_output=True)
  File "/Users/bsipocz/munka/devel/astroml/astroML/dimensionality/iterative_pca.py", line 107, in iterative_pca
    U, S, VT = np.linalg.svd(X_centered, full_matrices=False)
  File "/usr/local/lib/python3.7/site-packages/numpy/linalg/linalg.py", line 1562, in svd
    u, s, vh = gufunc(a, signature=signature, extobj=extobj)
  File "/usr/local/lib/python3.7/site-packages/numpy/linalg/linalg.py", line 98, in _raise_linalgerror_svd_nonconvergence
    raise LinAlgError("SVD did not converge")
numpy.linalg.linalg.LinAlgError: SVD did not converge
```

**Comment by bsipocz** [comment]
I can't reproduce this error with these dependency combination on v0.4:
```
Numpy: 1.16.4
Scipy: 1.3.0
Matplotlib: 3.1.0
Cython: 0.29.9
Astropy: 3.2rc2
scikit-learn: 0.21.2
```
