### ISSUE TITLE
can't run the demo chapter10 fig_line_wavelet_PSD

### ISSUE THREAD

**Issue by szad670401** [astroML/astroML#83]
I run the demo which on

http://www.astroml.org/book_figures/chapter10/fig_line_wavelet_PSD.html#book-fig-chapter10-fig-line-wavelet-psd

sh: latex: command not found
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/artist.py", line 55, in draw_wrapper
    draw(artist, renderer, _args, *_kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/figure.py", line 1034, in draw
    func(_args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/artist.py", line 55, in draw_wrapper
    draw(artist, renderer, *args, *_kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/axes.py", line 2086, in draw
    a.draw(renderer)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/artist.py", line 55, in draw_wrapper
    draw(artist, renderer, _args, *_kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/axis.py", line 1093, in draw
    renderer)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/axis.py", line 1042, in _get_tick_bboxes
    extent = tick.label1.get_window_extent(renderer)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/text.py", line 754, in get_window_extent
    bbox, info, descent = self._get_layout(self._renderer)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/text.py", line 329, in _get_layout
    ismath=ismath)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/backends/backend_macosx.py", line 147, in get_text_width_height_descent
    renderer=self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/texmanager.py", line 666, in get_text_width_height_descent
    dvifile = self.make_dvi(tex, fontsize)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/texmanager.py", line 413, in make_dvi
    'LaTeX: \n\n' % repr(tex)) + report)
RuntimeError: LaTeX was not able to process the following string:
'$-1.0$'
Here is the full report generated by LaTeX:

**Comment by jeremyblow** [comment]
I was able to reproduce this error on my platform, however the comment above `setup_text_plots(fontsize=8, usetex=True)` in `fig_line_wavelet_PSD.py` explains the cause quite well. By default, fonts will be rendered using LaTeX. If you do not have LaTeX support enabled on your system you will see the error you encoutered. You can change this default behavior by setting `usetex=False` in the script with the downside that fonts may not be render uniformly. 

Alternatively, you can install LaTeX on your system. Personally I use the [MacTeX distribution](https://www.tug.org/mactex/). Note you may need to restart your bash session for MPL to find the LaTeX support in your env path.

**Comment by bsipocz** [comment]
This issue seems to be solved by the workaround suggested above. If that is not the case and there is still some action items concerning the package, feel free to reopen in figure repository that is now refactored from the package code here: https://github.com/astroML/astroML_figures
