### ISSUE TITLE
[0.3] Test failures with numpy 1.12 (1.12 RC)

### ISSUE THREAD

**Issue by olebole** [astroML/astroML#90]
With numpy 1.12 (resp. 1.12 RC), several tests produce failures; mainly because of the incorrect usage of indices. One example:
```
ERROR: astroML.density_estimation.tests.test_hist_binwidth.test_freedman_bin_width
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/lib/python3/dist-packages/astroML/density_estimation/tests/test_hist_binwidth.py", line 18, in test_freedman_bin_width
    delta = freedman_bin_width(X)
  File "/usr/lib/python3/dist-packages/astroML/density_estimation/histtools.py", line 103, in freedman_bin_width
    v25 = dsorted[n / 4 - 1]
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```
Full build log [here](http://aws-logs.debian.net/2016/12/19/astroml_0.3-5_unstable.log). Corresponding Debian bug report [here](https://bugs.debian.org/848737).

**Comment by mkcedward** [comment]
Hi, I upgraded numpy to 1.13.3 and still met same exception.

Using the sample code from http://www.astroml.org/examples/algorithms/plot_bayesian_blocks.html#id4 and getting the following exception

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-4-a27f95e3febe> in <module>()
     14     # plot an adaptive-width histogram on top
     15     hist(t, bins=bins, ax=ax, color='black',
---> 16          histtype='step', normed=True, label=title)
     17 
     18     ax.legend(prop=dict(size=12))

/home/anaconda3/lib/python3.5/site-packages/astroML/plotting/hist_tools.py in hist(x, bins, range, *args, **kwargs)
     64         bins = bayesian_blocks(x)
     65     elif bins in ['knuth', 'knuths']:
---> 66         dx, bins = knuth_bin_width(x, True, disp=False)
     67     elif bins in ['scott', 'scotts']:
     68         dx, bins = scotts_bin_width(x, True)

/home/anaconda3/lib/python3.5/site-packages/astroML/density_estimation/histtools.py in knuth_bin_width(data, return_bins, disp)
    226     """
    227     knuthF = KnuthF(data)
--> 228     dx0, bins0 = freedman_bin_width(data, True)
    229     M0 = len(bins0) - 1
    230     M = optimize.fmin(knuthF, len(bins0), disp=disp)[0]

/home/anaconda3/lib/python3.5/site-packages/astroML/density_estimation/histtools.py in freedman_bin_width(data, return_bins)
    101 
    102     dsorted = np.sort(data)
--> 103     v25 = dsorted[n / 4 - 1]
    104     v75 = dsorted[(3 * n) / 4 - 1]
    105 

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

**Comment by bsipocz** [comment]
Thank you @olebole for reporting this. 
Right now `test_freedman_bin_width` passes when using 1.12, but there are still incompatibilities with newer numpy versions. 
We're working on the compatibilities, as well as on the removal of functionalities that have been moved upstream to astropy or other packages, so I'm closing this issue here now.
